Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "WOL & Shutdown Link Speed" -DisplayValue "Not Speed Down"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Power Saving Mode" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "NS Offload" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Jumbo Frame" -DisplayValue "9014 bytes"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Green Ethernet" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Gigabit Lite" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Energy-Efficient Ethernet" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Flow Control" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Interrupt Moderation" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Interrupt Moderation Rate" -DisplayValue "Off"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Enable PME" -DisplayValue "disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Maximum Number of RSS Queues" -DisplayValue "4 Queues"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Transmit Buffers" -DisplayValue "128"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Receive Buffers" -DisplayValue "512"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Large Send Offload V2 (IPv4)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Large Send Offload V2 (IPv6)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "TCP Checksum Offload (IPv4)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "TCP Checksum Offload (IPv6)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "UDP Checksum Offload (IPv4)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "UDP Checksum Offload (IPv6)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "IPv4 Checksum Offload" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Speed & Duplex" -DisplayValue "1.0 Gbps Full Duplex"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Gigabit Master Slave Mode" -DisplayValue "Force Slave Mode" For two NICs
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Maximum Number of RSS Processors" -DisplayValue "4 Processors"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "RSS load balancing profile" -DisplayValue "NUMAScaling"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Protocol ARP Offload" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Protocol NS Offload" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Ultra Low Power Mode" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Jumbo Packet" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Wake on Magic Packet" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Wake on Pattern Match" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Wake on Link Settings" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Wait for Link" -DisplayValue "off"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Energy Efficient Ethernet" -DisplayValue "Off"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Reduce Speed On Power Down" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "System Idle Power Saver" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Log Link State Event" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "*" -DisplayName "Packet Priority & VLAN" -DisplayValue "Packet Priority & VLAN Disabled"