:: Start with setting the location

pushd "%CD%"
CD /D "%~dp0"

:: Remove Telemetry
rmdir /s /q "C:\Program Files (x86)\Microsoft\EdgeUpdate"
rmdir /s /q "C:\Program Files (x86)\Microsoft\EdgeCore"
rmdir /s /q "C:\Program Files (x86)\Microsoft\EdgeWebview"
takeown /f "C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe"
rmdir /s /q "C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe"
rmdir /s /q "C:\Windows\SystemApps\Microsoft.Windows.AppRep.ChxApp_cw5n1h2txyewy"
rmdir /s /q "C:\Windows\SystemApps\microsoft.windows.narratorquickstart_8wekyb3d8bbwe"
rmdir /s /q "C:\Windows\SystemApps\Microsoft.Windows.PeopleExperienceHost_cw5n1h2txyewy"
rmdir /s /q "C:\Windows\SystemApps\ParentalControls_cw5n1h2txyewy"
del /F /Q "C:\Windows\System32\smartscreen.exe"
del /F /Q "C:\Windows\System32\GameBarPresenceWriter.exe"
del /F /Q "C:\Windows\System32\smartscreenps.dll"
del /F /Q "C:\Windows\System32\DeviceCensus.exe"
del /F /Q "C:\Windows\System32\CompatTelRunner.exe"
del /F /Q "C:\Windows\System32\dmclient.exe"
del /F /Q "C:\Windows\hh.exe"
del /F /Q "C:\Windows\HelpPane.exe"
del /F /Q "C:\Windows\System32\wermgr.exe"
del /F /Q "C:\Windows\System32\wersvc.dll"
del /F /Q "C:\Windows\System32\werui.dll"
del /F /Q "C:\Windows\System32\WerEnc.dll"
del /F /Q "C:\Windows\System32\WerFault.exe"
del /F /Q "C:\Windows\System32\wercplsupport.dll"
del /F /Q "C:\Windows\System32\werdiagcontroller.dll"
del /F /Q "C:\Windows\System32\WerEnc.dll"
del /F /Q "C:\Windows\System32\werui.dll"
del /F /Q "C:\Windows\System32\GamePanelExternalHook.dll
del /F /Q "C:\Windows\System32\gamemode.dll
del /F /Q "C:\Windows\System32\GameBarPresenceWriter.proxy.dll
del /F /Q "C:\Windows\System32\GamePanel.exe"
del /F /Q "C:\Windows\System32\gameux.dll"
del /F /Q "C:\Windows\System32\WerFaultSecure.exe"
del /F /Q "C:\Windows\System32\msfeeds.dll"
del /F /Q "C:\Windows\System32\MsSpellCheckingHost.exe"
del /F /Q "C:\Windows\System32\ieapfltr.dll"
del /F /Q "C:\Windows\System32\MsSpellCheckingFacility.dll"
del /F /Q "C:\Windows\System32\LocationNotificationWindows.exe"
del /F /Q "C:\Windows\System32\msfeedssync.exe"
del /F /Q "C:\Windows\winhlp32.exe"
del /F /Q "C:\Windows\System32\WpcMon.exe"
del /F /Q "C:\Windows\System32\atieclxx.exe"
